/* px - Wayland color picker (wlroots-only: needs wlr-layer-shell + wlr-screencopy)
 *
 * Port of the X11 px tool. Differences forced by the Wayland model:
 *
 *   - No XGetImage-on-root: pixel sampling instead comes from a single
 *     wlr-screencopy capture of the whole output, taken once at startup
 *     and held in memory. The magnifier/swatch therefore show a frozen
 *     frame of the desktop, not a live feed - this is the standard
 *     approach used by other Wayland pickers (hyprpicker, wl-color-picker)
 *     because screencopy is async/frame-based, not a synchronous
 *     "sample this pixel now" call.
 *
 *   - No floating root-positioned override-redirect windows: Wayland gives
 *     clients no global screen coordinate space to place windows in.
 *     Instead we open ONE fullscreen zwlr_layer_surface_v1 on the overlay
 *     layer with exclusive keyboard interactivity (replaces XGrabPointer +
 *     XGrabKeyboard), and draw the magnifier + swatch as panels positioned
 *     in *surface-local* coordinates near the simulated pointer.
 *
 *   - Single-output only: this build picks the first wl_output advertised
 *     and ignores the rest (multi-monitor correctness was explicitly
 *     dropped per user request, to keep this from becoming an output-
 *     hotplug/per-output-surface project).
 */

#define _DEFAULT_SOURCE
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <getopt.h>
#include <stdbool.h>
#include <string.h>
#include <errno.h>
#include <fcntl.h>
#include <math.h>
#include <sys/mman.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <sys/syscall.h>
#include <time.h>

#include <wayland-client.h>
#include <linux/input-event-codes.h>
#include <xkbcommon/xkbcommon.h>
#include <cairo/cairo.h>

/* =================================================================
 * Generated Wayland protocol code, inlined so this is a single,
 * self-contained source file with no separate header-generation
 * build step required. Originally produced by `wayland-scanner`
 * from the upstream protocol XML (kept untouched in protocols/, if
 * you ever need to regenerate this section).
 * ================================================================= */

/* ---- wlr-layer-shell-unstable-v1 client protocol header ---- */
/* Generated by wayland-scanner 1.22.0 */

#ifndef WLR_LAYER_SHELL_UNSTABLE_V1_CLIENT_PROTOCOL_H
#define WLR_LAYER_SHELL_UNSTABLE_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_wlr_layer_shell_unstable_v1 The wlr_layer_shell_unstable_v1 protocol
 * @section page_ifaces_wlr_layer_shell_unstable_v1 Interfaces
 * - @subpage page_iface_zwlr_layer_shell_v1 - create surfaces that are layers of the desktop
 * - @subpage page_iface_zwlr_layer_surface_v1 - layer metadata interface
 * @section page_copyright_wlr_layer_shell_unstable_v1 Copyright
 * <pre>
 *
 * Copyright © 2017 Drew DeVault
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 * </pre>
 */
struct wl_output;
struct wl_surface;
struct xdg_popup;
struct zwlr_layer_shell_v1;
struct zwlr_layer_surface_v1;

#ifndef ZWLR_LAYER_SHELL_V1_INTERFACE
#define ZWLR_LAYER_SHELL_V1_INTERFACE
/**
 * @page page_iface_zwlr_layer_shell_v1 zwlr_layer_shell_v1
 * @section page_iface_zwlr_layer_shell_v1_desc Description
 *
 * Clients can use this interface to assign the surface_layer role to
 * wl_surfaces. Such surfaces are assigned to a "layer" of the output and
 * rendered with a defined z-depth respective to each other. They may also be
 * anchored to the edges and corners of a screen and specify input handling
 * semantics. This interface should be suitable for the implementation of
 * many desktop shell components, and a broad number of other applications
 * that interact with the desktop.
 * @section page_iface_zwlr_layer_shell_v1_api API
 * See @ref iface_zwlr_layer_shell_v1.
 */
/**
 * @defgroup iface_zwlr_layer_shell_v1 The zwlr_layer_shell_v1 interface
 *
 * Clients can use this interface to assign the surface_layer role to
 * wl_surfaces. Such surfaces are assigned to a "layer" of the output and
 * rendered with a defined z-depth respective to each other. They may also be
 * anchored to the edges and corners of a screen and specify input handling
 * semantics. This interface should be suitable for the implementation of
 * many desktop shell components, and a broad number of other applications
 * that interact with the desktop.
 */
extern const struct wl_interface zwlr_layer_shell_v1_interface;
#endif
#ifndef ZWLR_LAYER_SURFACE_V1_INTERFACE
#define ZWLR_LAYER_SURFACE_V1_INTERFACE
/**
 * @page page_iface_zwlr_layer_surface_v1 zwlr_layer_surface_v1
 * @section page_iface_zwlr_layer_surface_v1_desc Description
 *
 * An interface that may be implemented by a wl_surface, for surfaces that
 * are designed to be rendered as a layer of a stacked desktop-like
 * environment.
 *
 * Layer surface state (layer, size, anchor, exclusive zone,
 * margin, interactivity) is double-buffered, and will be applied at the
 * time wl_surface.commit of the corresponding wl_surface is called.
 *
 * Attaching a null buffer to a layer surface unmaps it.
 *
 * Unmapping a layer_surface means that the surface cannot be shown by the
 * compositor until it is explicitly mapped again. The layer_surface
 * returns to the state it had right after layer_shell.get_layer_surface.
 * The client can re-map the surface by performing a commit without any
 * buffer attached, waiting for a configure event and handling it as usual.
 * @section page_iface_zwlr_layer_surface_v1_api API
 * See @ref iface_zwlr_layer_surface_v1.
 */
/**
 * @defgroup iface_zwlr_layer_surface_v1 The zwlr_layer_surface_v1 interface
 *
 * An interface that may be implemented by a wl_surface, for surfaces that
 * are designed to be rendered as a layer of a stacked desktop-like
 * environment.
 *
 * Layer surface state (layer, size, anchor, exclusive zone,
 * margin, interactivity) is double-buffered, and will be applied at the
 * time wl_surface.commit of the corresponding wl_surface is called.
 *
 * Attaching a null buffer to a layer surface unmaps it.
 *
 * Unmapping a layer_surface means that the surface cannot be shown by the
 * compositor until it is explicitly mapped again. The layer_surface
 * returns to the state it had right after layer_shell.get_layer_surface.
 * The client can re-map the surface by performing a commit without any
 * buffer attached, waiting for a configure event and handling it as usual.
 */
extern const struct wl_interface zwlr_layer_surface_v1_interface;
#endif

#ifndef ZWLR_LAYER_SHELL_V1_ERROR_ENUM
#define ZWLR_LAYER_SHELL_V1_ERROR_ENUM
enum zwlr_layer_shell_v1_error {
	/**
	 * wl_surface has another role
	 */
	ZWLR_LAYER_SHELL_V1_ERROR_ROLE = 0,
	/**
	 * layer value is invalid
	 */
	ZWLR_LAYER_SHELL_V1_ERROR_INVALID_LAYER = 1,
	/**
	 * wl_surface has a buffer attached or committed
	 */
	ZWLR_LAYER_SHELL_V1_ERROR_ALREADY_CONSTRUCTED = 2,
};
#endif /* ZWLR_LAYER_SHELL_V1_ERROR_ENUM */

#ifndef ZWLR_LAYER_SHELL_V1_LAYER_ENUM
#define ZWLR_LAYER_SHELL_V1_LAYER_ENUM
/**
 * @ingroup iface_zwlr_layer_shell_v1
 * available layers for surfaces
 *
 * These values indicate which layers a surface can be rendered in. They
 * are ordered by z depth, bottom-most first. Traditional shell surfaces
 * will typically be rendered between the bottom and top layers.
 * Fullscreen shell surfaces are typically rendered at the top layer.
 * Multiple surfaces can share a single layer, and ordering within a
 * single layer is undefined.
 */
enum zwlr_layer_shell_v1_layer {
	ZWLR_LAYER_SHELL_V1_LAYER_BACKGROUND = 0,
	ZWLR_LAYER_SHELL_V1_LAYER_BOTTOM = 1,
	ZWLR_LAYER_SHELL_V1_LAYER_TOP = 2,
	ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY = 3,
};
#endif /* ZWLR_LAYER_SHELL_V1_LAYER_ENUM */

#define ZWLR_LAYER_SHELL_V1_GET_LAYER_SURFACE 0
#define ZWLR_LAYER_SHELL_V1_DESTROY 1


/**
 * @ingroup iface_zwlr_layer_shell_v1
 */
#define ZWLR_LAYER_SHELL_V1_GET_LAYER_SURFACE_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_shell_v1
 */
#define ZWLR_LAYER_SHELL_V1_DESTROY_SINCE_VERSION 3

/** @ingroup iface_zwlr_layer_shell_v1 */
static inline void
zwlr_layer_shell_v1_set_user_data(struct zwlr_layer_shell_v1 *zwlr_layer_shell_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) zwlr_layer_shell_v1, user_data);
}

/** @ingroup iface_zwlr_layer_shell_v1 */
static inline void *
zwlr_layer_shell_v1_get_user_data(struct zwlr_layer_shell_v1 *zwlr_layer_shell_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) zwlr_layer_shell_v1);
}

static inline uint32_t
zwlr_layer_shell_v1_get_version(struct zwlr_layer_shell_v1 *zwlr_layer_shell_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) zwlr_layer_shell_v1);
}

/**
 * @ingroup iface_zwlr_layer_shell_v1
 *
 * Create a layer surface for an existing surface. This assigns the role of
 * layer_surface, or raises a protocol error if another role is already
 * assigned.
 *
 * Creating a layer surface from a wl_surface which has a buffer attached
 * or committed is a client error, and any attempts by a client to attach
 * or manipulate a buffer prior to the first layer_surface.configure call
 * must also be treated as errors.
 *
 * After creating a layer_surface object and setting it up, the client
 * must perform an initial commit without any buffer attached.
 * The compositor will reply with a layer_surface.configure event.
 * The client must acknowledge it and is then allowed to attach a buffer
 * to map the surface.
 *
 * You may pass NULL for output to allow the compositor to decide which
 * output to use. Generally this will be the one that the user most
 * recently interacted with.
 *
 * Clients can specify a namespace that defines the purpose of the layer
 * surface.
 */
static inline struct zwlr_layer_surface_v1 *
zwlr_layer_shell_v1_get_layer_surface(struct zwlr_layer_shell_v1 *zwlr_layer_shell_v1, struct wl_surface *surface, struct wl_output *output, uint32_t layer, const char *namespace)
{
	struct wl_proxy *id;

	id = wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_shell_v1,
			 ZWLR_LAYER_SHELL_V1_GET_LAYER_SURFACE, &zwlr_layer_surface_v1_interface, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_shell_v1), 0, NULL, surface, output, layer, namespace);

	return (struct zwlr_layer_surface_v1 *) id;
}

/**
 * @ingroup iface_zwlr_layer_shell_v1
 *
 * This request indicates that the client will not use the layer_shell
 * object any more. Objects that have been created through this instance
 * are not affected.
 */
static inline void
zwlr_layer_shell_v1_destroy(struct zwlr_layer_shell_v1 *zwlr_layer_shell_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_shell_v1,
			 ZWLR_LAYER_SHELL_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_shell_v1), WL_MARSHAL_FLAG_DESTROY);
}

#ifndef ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ENUM
#define ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ENUM
/**
 * @ingroup iface_zwlr_layer_surface_v1
 * types of keyboard interaction possible for a layer shell surface
 *
 * Types of keyboard interaction possible for layer shell surfaces. The
 * rationale for this is twofold: (1) some applications are not interested
 * in keyboard events and not allowing them to be focused can improve the
 * desktop experience; (2) some applications will want to take exclusive
 * keyboard focus.
 */
enum zwlr_layer_surface_v1_keyboard_interactivity {
	/**
	 * no keyboard focus is possible
	 *
	 * This value indicates that this surface is not interested in
	 * keyboard events and the compositor should never assign it the
	 * keyboard focus.
	 *
	 * This is the default value, set for newly created layer shell
	 * surfaces.
	 *
	 * This is useful for e.g. desktop widgets that display information
	 * or only have interaction with non-keyboard input devices.
	 */
	ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_NONE = 0,
	/**
	 * request exclusive keyboard focus
	 *
	 * Request exclusive keyboard focus if this surface is above the
	 * shell surface layer.
	 *
	 * For the top and overlay layers, the seat will always give
	 * exclusive keyboard focus to the top-most layer which has
	 * keyboard interactivity set to exclusive. If this layer contains
	 * multiple surfaces with keyboard interactivity set to exclusive,
	 * the compositor determines the one receiving keyboard events in
	 * an implementation- defined manner. In this case, no guarantee is
	 * made when this surface will receive keyboard focus (if ever).
	 *
	 * For the bottom and background layers, the compositor is allowed
	 * to use normal focus semantics.
	 *
	 * This setting is mainly intended for applications that need to
	 * ensure they receive all keyboard events, such as a lock screen
	 * or a password prompt.
	 */
	ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_EXCLUSIVE = 1,
	/**
	 * request regular keyboard focus semantics
	 *
	 * This requests the compositor to allow this surface to be
	 * focused and unfocused by the user in an implementation-defined
	 * manner. The user should be able to unfocus this surface even
	 * regardless of the layer it is on.
	 *
	 * Typically, the compositor will want to use its normal mechanism
	 * to manage keyboard focus between layer shell surfaces with this
	 * setting and regular toplevels on the desktop layer (e.g. click
	 * to focus). Nevertheless, it is possible for a compositor to
	 * require a special interaction to focus or unfocus layer shell
	 * surfaces (e.g. requiring a click even if focus follows the mouse
	 * normally, or providing a keybinding to switch focus between
	 * layers).
	 *
	 * This setting is mainly intended for desktop shell components
	 * (e.g. panels) that allow keyboard interaction. Using this option
	 * can allow implementing a desktop shell that can be fully usable
	 * without the mouse.
	 * @since 4
	 */
	ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ON_DEMAND = 2,
};
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ON_DEMAND_SINCE_VERSION 4
#endif /* ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_ENUM */

#ifndef ZWLR_LAYER_SURFACE_V1_ERROR_ENUM
#define ZWLR_LAYER_SURFACE_V1_ERROR_ENUM
enum zwlr_layer_surface_v1_error {
	/**
	 * provided surface state is invalid
	 */
	ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_SURFACE_STATE = 0,
	/**
	 * size is invalid
	 */
	ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_SIZE = 1,
	/**
	 * anchor bitfield is invalid
	 */
	ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_ANCHOR = 2,
	/**
	 * keyboard interactivity is invalid
	 */
	ZWLR_LAYER_SURFACE_V1_ERROR_INVALID_KEYBOARD_INTERACTIVITY = 3,
};
#endif /* ZWLR_LAYER_SURFACE_V1_ERROR_ENUM */

#ifndef ZWLR_LAYER_SURFACE_V1_ANCHOR_ENUM
#define ZWLR_LAYER_SURFACE_V1_ANCHOR_ENUM
enum zwlr_layer_surface_v1_anchor {
	/**
	 * the top edge of the anchor rectangle
	 */
	ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP = 1,
	/**
	 * the bottom edge of the anchor rectangle
	 */
	ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM = 2,
	/**
	 * the left edge of the anchor rectangle
	 */
	ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT = 4,
	/**
	 * the right edge of the anchor rectangle
	 */
	ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT = 8,
};
#endif /* ZWLR_LAYER_SURFACE_V1_ANCHOR_ENUM */

/**
 * @ingroup iface_zwlr_layer_surface_v1
 * @struct zwlr_layer_surface_v1_listener
 */
struct zwlr_layer_surface_v1_listener {
	/**
	 * suggest a surface change
	 *
	 * The configure event asks the client to resize its surface.
	 *
	 * Clients should arrange their surface for the new states, and
	 * then send an ack_configure request with the serial sent in this
	 * configure event at some point before committing the new surface.
	 *
	 * The client is free to dismiss all but the last configure event
	 * it received.
	 *
	 * The width and height arguments specify the size of the window in
	 * surface-local coordinates.
	 *
	 * The size is a hint, in the sense that the client is free to
	 * ignore it if it doesn't resize, pick a smaller size (to satisfy
	 * aspect ratio or resize in steps of NxM pixels). If the client
	 * picks a smaller size and is anchored to two opposite anchors
	 * (e.g. 'top' and 'bottom'), the surface will be centered on this
	 * axis.
	 *
	 * If the width or height arguments are zero, it means the client
	 * should decide its own window dimension.
	 */
	void (*configure)(void *data,
			  struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1,
			  uint32_t serial,
			  uint32_t width,
			  uint32_t height);
	/**
	 * surface should be closed
	 *
	 * The closed event is sent by the compositor when the surface
	 * will no longer be shown. The output may have been destroyed or
	 * the user may have asked for it to be removed. Further changes to
	 * the surface will be ignored. The client should destroy the
	 * resource after receiving this event, and create a new surface if
	 * they so choose.
	 */
	void (*closed)(void *data,
		       struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1);
};

/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
static inline int
zwlr_layer_surface_v1_add_listener(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1,
				   const struct zwlr_layer_surface_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) zwlr_layer_surface_v1,
				     (void (**)(void)) listener, data);
}

#define ZWLR_LAYER_SURFACE_V1_SET_SIZE 0
#define ZWLR_LAYER_SURFACE_V1_SET_ANCHOR 1
#define ZWLR_LAYER_SURFACE_V1_SET_EXCLUSIVE_ZONE 2
#define ZWLR_LAYER_SURFACE_V1_SET_MARGIN 3
#define ZWLR_LAYER_SURFACE_V1_SET_KEYBOARD_INTERACTIVITY 4
#define ZWLR_LAYER_SURFACE_V1_GET_POPUP 5
#define ZWLR_LAYER_SURFACE_V1_ACK_CONFIGURE 6
#define ZWLR_LAYER_SURFACE_V1_DESTROY 7
#define ZWLR_LAYER_SURFACE_V1_SET_LAYER 8

/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_CONFIGURE_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_CLOSED_SINCE_VERSION 1

/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_SIZE_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_ANCHOR_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_EXCLUSIVE_ZONE_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_MARGIN_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_KEYBOARD_INTERACTIVITY_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_GET_POPUP_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_ACK_CONFIGURE_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_layer_surface_v1
 */
#define ZWLR_LAYER_SURFACE_V1_SET_LAYER_SINCE_VERSION 2

/** @ingroup iface_zwlr_layer_surface_v1 */
static inline void
zwlr_layer_surface_v1_set_user_data(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) zwlr_layer_surface_v1, user_data);
}

/** @ingroup iface_zwlr_layer_surface_v1 */
static inline void *
zwlr_layer_surface_v1_get_user_data(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) zwlr_layer_surface_v1);
}

static inline uint32_t
zwlr_layer_surface_v1_get_version(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) zwlr_layer_surface_v1);
}

/**
 * @ingroup iface_zwlr_layer_surface_v1
 *
 * Sets the size of the surface in surface-local coordinates. The
 * compositor will display the surface centered with respect to its
 * anchors.
 *
 * If you pass 0 for either value, the compositor will assign it and
 * inform you of the assignment in the configure event. You must set your
 * anchor to opposite edges in the dimensions you omit; not doing so is a
 * protocol error. Both values are 0 by default.
 *
 * Size is double-buffered, see wl_surface.commit.
 */
static inline void
zwlr_layer_surface_v1_set_size(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1, uint32_t width, uint32_t height)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_surface_v1,
			 ZWLR_LAYER_SURFACE_V1_SET_SIZE, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_surface_v1), 0, width, height);
}

/**
 * @ingroup iface_zwlr_layer_surface_v1
 *
 * Requests that the compositor anchor the surface to the specified edges
 * and corners. If two orthogonal edges are specified (e.g. 'top' and
 * 'left'), then the anchor point will be the intersection of the edges
 * (e.g. the top left corner of the output); otherwise the anchor point
 * will be centered on that edge, or in the center if none is specified.
 *
 * Anchor is double-buffered, see wl_surface.commit.
 */
static inline void
zwlr_layer_surface_v1_set_anchor(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1, uint32_t anchor)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_surface_v1,
			 ZWLR_LAYER_SURFACE_V1_SET_ANCHOR, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_surface_v1), 0, anchor);
}

/**
 * @ingroup iface_zwlr_layer_surface_v1
 *
 * Requests that the compositor avoids occluding an area with other
 * surfaces. The compositor's use of this information is
 * implementation-dependent - do not assume that this region will not
 * actually be occluded.
 *
 * A positive value is only meaningful if the surface is anchored to one
 * edge or an edge and both perpendicular edges. If the surface is not
 * anchored, anchored to only two perpendicular edges (a corner), anchored
 * to only two parallel edges or anchored to all edges, a positive value
 * will be treated the same as zero.
 *
 * A positive zone is the distance from the edge in surface-local
 * coordinates to consider exclusive.
 *
 * Surfaces that do not wish to have an exclusive zone may instead specify
 * how they should interact with surfaces that do. If set to zero, the
 * surface indicates that it would like to be moved to avoid occluding
 * surfaces with a positive exclusive zone. If set to -1, the surface
 * indicates that it would not like to be moved to accommodate for other
 * surfaces, and the compositor should extend it all the way to the edges
 * it is anchored to.
 *
 * For example, a panel might set its exclusive zone to 10, so that
 * maximized shell surfaces are not shown on top of it. A notification
 * might set its exclusive zone to 0, so that it is moved to avoid
 * occluding the panel, but shell surfaces are shown underneath it. A
 * wallpaper or lock screen might set their exclusive zone to -1, so that
 * they stretch below or over the panel.
 *
 * The default value is 0.
 *
 * Exclusive zone is double-buffered, see wl_surface.commit.
 */
static inline void
zwlr_layer_surface_v1_set_exclusive_zone(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1, int32_t zone)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_surface_v1,
			 ZWLR_LAYER_SURFACE_V1_SET_EXCLUSIVE_ZONE, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_surface_v1), 0, zone);
}

/**
 * @ingroup iface_zwlr_layer_surface_v1
 *
 * Requests that the surface be placed some distance away from the anchor
 * point on the output, in surface-local coordinates. Setting this value
 * for edges you are not anchored to has no effect.
 *
 * The exclusive zone includes the margin.
 *
 * Margin is double-buffered, see wl_surface.commit.
 */
static inline void
zwlr_layer_surface_v1_set_margin(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1, int32_t top, int32_t right, int32_t bottom, int32_t left)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_surface_v1,
			 ZWLR_LAYER_SURFACE_V1_SET_MARGIN, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_surface_v1), 0, top, right, bottom, left);
}

/**
 * @ingroup iface_zwlr_layer_surface_v1
 *
 * Set how keyboard events are delivered to this surface. By default,
 * layer shell surfaces do not receive keyboard events; this request can
 * be used to change this.
 *
 * This setting is inherited by child surfaces set by the get_popup
 * request.
 *
 * Layer surfaces receive pointer, touch, and tablet events normally. If
 * you do not want to receive them, set the input region on your surface
 * to an empty region.
 *
 * Keyboard interactivity is double-buffered, see wl_surface.commit.
 */
static inline void
zwlr_layer_surface_v1_set_keyboard_interactivity(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1, uint32_t keyboard_interactivity)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_surface_v1,
			 ZWLR_LAYER_SURFACE_V1_SET_KEYBOARD_INTERACTIVITY, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_surface_v1), 0, keyboard_interactivity);
}

/**
 * @ingroup iface_zwlr_layer_surface_v1
 *
 * This assigns an xdg_popup's parent to this layer_surface.  This popup
 * should have been created via xdg_surface::get_popup with the parent set
 * to NULL, and this request must be invoked before committing the popup's
 * initial state.
 *
 * See the documentation of xdg_popup for more details about what an
 * xdg_popup is and how it is used.
 */
static inline void
zwlr_layer_surface_v1_get_popup(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1, struct xdg_popup *popup)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_surface_v1,
			 ZWLR_LAYER_SURFACE_V1_GET_POPUP, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_surface_v1), 0, popup);
}

/**
 * @ingroup iface_zwlr_layer_surface_v1
 *
 * When a configure event is received, if a client commits the
 * surface in response to the configure event, then the client
 * must make an ack_configure request sometime before the commit
 * request, passing along the serial of the configure event.
 *
 * If the client receives multiple configure events before it
 * can respond to one, it only has to ack the last configure event.
 *
 * A client is not required to commit immediately after sending
 * an ack_configure request - it may even ack_configure several times
 * before its next surface commit.
 *
 * A client may send multiple ack_configure requests before committing, but
 * only the last request sent before a commit indicates which configure
 * event the client really is responding to.
 */
static inline void
zwlr_layer_surface_v1_ack_configure(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1, uint32_t serial)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_surface_v1,
			 ZWLR_LAYER_SURFACE_V1_ACK_CONFIGURE, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_surface_v1), 0, serial);
}

/**
 * @ingroup iface_zwlr_layer_surface_v1
 *
 * This request destroys the layer surface.
 */
static inline void
zwlr_layer_surface_v1_destroy(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_surface_v1,
			 ZWLR_LAYER_SURFACE_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_surface_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_zwlr_layer_surface_v1
 *
 * Change the layer that the surface is rendered on.
 *
 * Layer is double-buffered, see wl_surface.commit.
 */
static inline void
zwlr_layer_surface_v1_set_layer(struct zwlr_layer_surface_v1 *zwlr_layer_surface_v1, uint32_t layer)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_layer_surface_v1,
			 ZWLR_LAYER_SURFACE_V1_SET_LAYER, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_layer_surface_v1), 0, layer);
}

#ifdef  __cplusplus
}
#endif

#endif

/* ---- wlr-screencopy-unstable-v1 client protocol header ---- */
/* Generated by wayland-scanner 1.22.0 */

#ifndef WLR_SCREENCOPY_UNSTABLE_V1_CLIENT_PROTOCOL_H
#define WLR_SCREENCOPY_UNSTABLE_V1_CLIENT_PROTOCOL_H

#include <stdint.h>
#include <stddef.h>
#include "wayland-client.h"

#ifdef  __cplusplus
extern "C" {
#endif

/**
 * @page page_wlr_screencopy_unstable_v1 The wlr_screencopy_unstable_v1 protocol
 * screen content capturing on client buffers
 *
 * @section page_desc_wlr_screencopy_unstable_v1 Description
 *
 * This protocol allows clients to ask the compositor to copy part of the
 * screen content to a client buffer.
 *
 * Warning! The protocol described in this file is experimental and
 * backward incompatible changes may be made. Backward compatible changes
 * may be added together with the corresponding interface version bump.
 * Backward incompatible changes are done by bumping the version number in
 * the protocol and interface names and resetting the interface version.
 * Once the protocol is to be declared stable, the 'z' prefix and the
 * version number in the protocol and interface names are removed and the
 * interface version number is reset.
 *
 * @section page_ifaces_wlr_screencopy_unstable_v1 Interfaces
 * - @subpage page_iface_zwlr_screencopy_manager_v1 - manager to inform clients and begin capturing
 * - @subpage page_iface_zwlr_screencopy_frame_v1 - a frame ready for copy
 * @section page_copyright_wlr_screencopy_unstable_v1 Copyright
 * <pre>
 *
 * Copyright © 2018 Simon Ser
 * Copyright © 2019 Andri Yngvason
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 * </pre>
 */
struct wl_buffer;
struct wl_output;
struct zwlr_screencopy_frame_v1;
struct zwlr_screencopy_manager_v1;

#ifndef ZWLR_SCREENCOPY_MANAGER_V1_INTERFACE
#define ZWLR_SCREENCOPY_MANAGER_V1_INTERFACE
/**
 * @page page_iface_zwlr_screencopy_manager_v1 zwlr_screencopy_manager_v1
 * @section page_iface_zwlr_screencopy_manager_v1_desc Description
 *
 * This object is a manager which offers requests to start capturing from a
 * source.
 * @section page_iface_zwlr_screencopy_manager_v1_api API
 * See @ref iface_zwlr_screencopy_manager_v1.
 */
/**
 * @defgroup iface_zwlr_screencopy_manager_v1 The zwlr_screencopy_manager_v1 interface
 *
 * This object is a manager which offers requests to start capturing from a
 * source.
 */
extern const struct wl_interface zwlr_screencopy_manager_v1_interface;
#endif
#ifndef ZWLR_SCREENCOPY_FRAME_V1_INTERFACE
#define ZWLR_SCREENCOPY_FRAME_V1_INTERFACE
/**
 * @page page_iface_zwlr_screencopy_frame_v1 zwlr_screencopy_frame_v1
 * @section page_iface_zwlr_screencopy_frame_v1_desc Description
 *
 * This object represents a single frame.
 *
 * When created, a series of buffer events will be sent, each representing a
 * supported buffer type. The "buffer_done" event is sent afterwards to
 * indicate that all supported buffer types have been enumerated. The client
 * will then be able to send a "copy" request. If the capture is successful,
 * the compositor will send a "flags" followed by a "ready" event.
 *
 * For objects version 2 or lower, wl_shm buffers are always supported, ie.
 * the "buffer" event is guaranteed to be sent.
 *
 * If the capture failed, the "failed" event is sent. This can happen anytime
 * before the "ready" event.
 *
 * Once either a "ready" or a "failed" event is received, the client should
 * destroy the frame.
 * @section page_iface_zwlr_screencopy_frame_v1_api API
 * See @ref iface_zwlr_screencopy_frame_v1.
 */
/**
 * @defgroup iface_zwlr_screencopy_frame_v1 The zwlr_screencopy_frame_v1 interface
 *
 * This object represents a single frame.
 *
 * When created, a series of buffer events will be sent, each representing a
 * supported buffer type. The "buffer_done" event is sent afterwards to
 * indicate that all supported buffer types have been enumerated. The client
 * will then be able to send a "copy" request. If the capture is successful,
 * the compositor will send a "flags" followed by a "ready" event.
 *
 * For objects version 2 or lower, wl_shm buffers are always supported, ie.
 * the "buffer" event is guaranteed to be sent.
 *
 * If the capture failed, the "failed" event is sent. This can happen anytime
 * before the "ready" event.
 *
 * Once either a "ready" or a "failed" event is received, the client should
 * destroy the frame.
 */
extern const struct wl_interface zwlr_screencopy_frame_v1_interface;
#endif

#define ZWLR_SCREENCOPY_MANAGER_V1_CAPTURE_OUTPUT 0
#define ZWLR_SCREENCOPY_MANAGER_V1_CAPTURE_OUTPUT_REGION 1
#define ZWLR_SCREENCOPY_MANAGER_V1_DESTROY 2


/**
 * @ingroup iface_zwlr_screencopy_manager_v1
 */
#define ZWLR_SCREENCOPY_MANAGER_V1_CAPTURE_OUTPUT_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_screencopy_manager_v1
 */
#define ZWLR_SCREENCOPY_MANAGER_V1_CAPTURE_OUTPUT_REGION_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_screencopy_manager_v1
 */
#define ZWLR_SCREENCOPY_MANAGER_V1_DESTROY_SINCE_VERSION 1

/** @ingroup iface_zwlr_screencopy_manager_v1 */
static inline void
zwlr_screencopy_manager_v1_set_user_data(struct zwlr_screencopy_manager_v1 *zwlr_screencopy_manager_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) zwlr_screencopy_manager_v1, user_data);
}

/** @ingroup iface_zwlr_screencopy_manager_v1 */
static inline void *
zwlr_screencopy_manager_v1_get_user_data(struct zwlr_screencopy_manager_v1 *zwlr_screencopy_manager_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) zwlr_screencopy_manager_v1);
}

static inline uint32_t
zwlr_screencopy_manager_v1_get_version(struct zwlr_screencopy_manager_v1 *zwlr_screencopy_manager_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) zwlr_screencopy_manager_v1);
}

/**
 * @ingroup iface_zwlr_screencopy_manager_v1
 *
 * Capture the next frame of an entire output.
 */
static inline struct zwlr_screencopy_frame_v1 *
zwlr_screencopy_manager_v1_capture_output(struct zwlr_screencopy_manager_v1 *zwlr_screencopy_manager_v1, int32_t overlay_cursor, struct wl_output *output)
{
	struct wl_proxy *frame;

	frame = wl_proxy_marshal_flags((struct wl_proxy *) zwlr_screencopy_manager_v1,
			 ZWLR_SCREENCOPY_MANAGER_V1_CAPTURE_OUTPUT, &zwlr_screencopy_frame_v1_interface, wl_proxy_get_version((struct wl_proxy *) zwlr_screencopy_manager_v1), 0, NULL, overlay_cursor, output);

	return (struct zwlr_screencopy_frame_v1 *) frame;
}

/**
 * @ingroup iface_zwlr_screencopy_manager_v1
 *
 * Capture the next frame of an output's region.
 *
 * The region is given in output logical coordinates, see
 * xdg_output.logical_size. The region will be clipped to the output's
 * extents.
 */
static inline struct zwlr_screencopy_frame_v1 *
zwlr_screencopy_manager_v1_capture_output_region(struct zwlr_screencopy_manager_v1 *zwlr_screencopy_manager_v1, int32_t overlay_cursor, struct wl_output *output, int32_t x, int32_t y, int32_t width, int32_t height)
{
	struct wl_proxy *frame;

	frame = wl_proxy_marshal_flags((struct wl_proxy *) zwlr_screencopy_manager_v1,
			 ZWLR_SCREENCOPY_MANAGER_V1_CAPTURE_OUTPUT_REGION, &zwlr_screencopy_frame_v1_interface, wl_proxy_get_version((struct wl_proxy *) zwlr_screencopy_manager_v1), 0, NULL, overlay_cursor, output, x, y, width, height);

	return (struct zwlr_screencopy_frame_v1 *) frame;
}

/**
 * @ingroup iface_zwlr_screencopy_manager_v1
 *
 * All objects created by the manager will still remain valid, until their
 * appropriate destroy request has been called.
 */
static inline void
zwlr_screencopy_manager_v1_destroy(struct zwlr_screencopy_manager_v1 *zwlr_screencopy_manager_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_screencopy_manager_v1,
			 ZWLR_SCREENCOPY_MANAGER_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_screencopy_manager_v1), WL_MARSHAL_FLAG_DESTROY);
}

#ifndef ZWLR_SCREENCOPY_FRAME_V1_ERROR_ENUM
#define ZWLR_SCREENCOPY_FRAME_V1_ERROR_ENUM
enum zwlr_screencopy_frame_v1_error {
	/**
	 * the object has already been used to copy a wl_buffer
	 */
	ZWLR_SCREENCOPY_FRAME_V1_ERROR_ALREADY_USED = 0,
	/**
	 * buffer attributes are invalid
	 */
	ZWLR_SCREENCOPY_FRAME_V1_ERROR_INVALID_BUFFER = 1,
};
#endif /* ZWLR_SCREENCOPY_FRAME_V1_ERROR_ENUM */

#ifndef ZWLR_SCREENCOPY_FRAME_V1_FLAGS_ENUM
#define ZWLR_SCREENCOPY_FRAME_V1_FLAGS_ENUM
enum zwlr_screencopy_frame_v1_flags {
	/**
	 * contents are y-inverted
	 */
	ZWLR_SCREENCOPY_FRAME_V1_FLAGS_Y_INVERT = 1,
};
#endif /* ZWLR_SCREENCOPY_FRAME_V1_FLAGS_ENUM */

/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 * @struct zwlr_screencopy_frame_v1_listener
 */
struct zwlr_screencopy_frame_v1_listener {
	/**
	 * wl_shm buffer information
	 *
	 * Provides information about wl_shm buffer parameters that need
	 * to be used for this frame. This event is sent once after the
	 * frame is created if wl_shm buffers are supported.
	 * @param format buffer format
	 * @param width buffer width
	 * @param height buffer height
	 * @param stride buffer stride
	 */
	void (*buffer)(void *data,
		       struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1,
		       uint32_t format,
		       uint32_t width,
		       uint32_t height,
		       uint32_t stride);
	/**
	 * frame flags
	 *
	 * Provides flags about the frame. This event is sent once before
	 * the "ready" event.
	 * @param flags frame flags
	 */
	void (*flags)(void *data,
		      struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1,
		      uint32_t flags);
	/**
	 * indicates frame is available for reading
	 *
	 * Called as soon as the frame is copied, indicating it is
	 * available for reading. This event includes the time at which
	 * presentation happened at.
	 *
	 * The timestamp is expressed as tv_sec_hi, tv_sec_lo, tv_nsec
	 * triples, each component being an unsigned 32-bit value. Whole
	 * seconds are in tv_sec which is a 64-bit value combined from
	 * tv_sec_hi and tv_sec_lo, and the additional fractional part in
	 * tv_nsec as nanoseconds. Hence, for valid timestamps tv_nsec must
	 * be in [0, 999999999]. The seconds part may have an arbitrary
	 * offset at start.
	 *
	 * After receiving this event, the client should destroy the
	 * object.
	 * @param tv_sec_hi high 32 bits of the seconds part of the timestamp
	 * @param tv_sec_lo low 32 bits of the seconds part of the timestamp
	 * @param tv_nsec nanoseconds part of the timestamp
	 */
	void (*ready)(void *data,
		      struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1,
		      uint32_t tv_sec_hi,
		      uint32_t tv_sec_lo,
		      uint32_t tv_nsec);
	/**
	 * frame copy failed
	 *
	 * This event indicates that the attempted frame copy has failed.
	 *
	 * After receiving this event, the client should destroy the
	 * object.
	 */
	void (*failed)(void *data,
		       struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1);
	/**
	 * carries the coordinates of the damaged region
	 *
	 * This event is sent right before the ready event when
	 * copy_with_damage is requested. It may be generated multiple
	 * times for each copy_with_damage request.
	 *
	 * The arguments describe a box around an area that has changed
	 * since the last copy request that was derived from the current
	 * screencopy manager instance.
	 *
	 * The union of all regions received between the call to
	 * copy_with_damage and a ready event is the total damage since the
	 * prior ready event.
	 * @param x damaged x coordinates
	 * @param y damaged y coordinates
	 * @param width current width
	 * @param height current height
	 * @since 2
	 */
	void (*damage)(void *data,
		       struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1,
		       uint32_t x,
		       uint32_t y,
		       uint32_t width,
		       uint32_t height);
	/**
	 * linux-dmabuf buffer information
	 *
	 * Provides information about linux-dmabuf buffer parameters that
	 * need to be used for this frame. This event is sent once after
	 * the frame is created if linux-dmabuf buffers are supported.
	 * @param format fourcc pixel format
	 * @param width buffer width
	 * @param height buffer height
	 * @since 3
	 */
	void (*linux_dmabuf)(void *data,
			     struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1,
			     uint32_t format,
			     uint32_t width,
			     uint32_t height);
	/**
	 * all buffer types reported
	 *
	 * This event is sent once after all buffer events have been
	 * sent.
	 *
	 * The client should proceed to create a buffer of one of the
	 * supported types, and send a "copy" request.
	 * @since 3
	 */
	void (*buffer_done)(void *data,
			    struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1);
};

/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
static inline int
zwlr_screencopy_frame_v1_add_listener(struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1,
				      const struct zwlr_screencopy_frame_v1_listener *listener, void *data)
{
	return wl_proxy_add_listener((struct wl_proxy *) zwlr_screencopy_frame_v1,
				     (void (**)(void)) listener, data);
}

#define ZWLR_SCREENCOPY_FRAME_V1_COPY 0
#define ZWLR_SCREENCOPY_FRAME_V1_DESTROY 1
#define ZWLR_SCREENCOPY_FRAME_V1_COPY_WITH_DAMAGE 2

/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
#define ZWLR_SCREENCOPY_FRAME_V1_BUFFER_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
#define ZWLR_SCREENCOPY_FRAME_V1_FLAGS_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
#define ZWLR_SCREENCOPY_FRAME_V1_READY_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
#define ZWLR_SCREENCOPY_FRAME_V1_FAILED_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
#define ZWLR_SCREENCOPY_FRAME_V1_DAMAGE_SINCE_VERSION 2
/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
#define ZWLR_SCREENCOPY_FRAME_V1_LINUX_DMABUF_SINCE_VERSION 3
/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
#define ZWLR_SCREENCOPY_FRAME_V1_BUFFER_DONE_SINCE_VERSION 3

/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
#define ZWLR_SCREENCOPY_FRAME_V1_COPY_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
#define ZWLR_SCREENCOPY_FRAME_V1_DESTROY_SINCE_VERSION 1
/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 */
#define ZWLR_SCREENCOPY_FRAME_V1_COPY_WITH_DAMAGE_SINCE_VERSION 2

/** @ingroup iface_zwlr_screencopy_frame_v1 */
static inline void
zwlr_screencopy_frame_v1_set_user_data(struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1, void *user_data)
{
	wl_proxy_set_user_data((struct wl_proxy *) zwlr_screencopy_frame_v1, user_data);
}

/** @ingroup iface_zwlr_screencopy_frame_v1 */
static inline void *
zwlr_screencopy_frame_v1_get_user_data(struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1)
{
	return wl_proxy_get_user_data((struct wl_proxy *) zwlr_screencopy_frame_v1);
}

static inline uint32_t
zwlr_screencopy_frame_v1_get_version(struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1)
{
	return wl_proxy_get_version((struct wl_proxy *) zwlr_screencopy_frame_v1);
}

/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 *
 * Copy the frame to the supplied buffer. The buffer must have a the
 * correct size, see zwlr_screencopy_frame_v1.buffer and
 * zwlr_screencopy_frame_v1.linux_dmabuf. The buffer needs to have a
 * supported format.
 *
 * If the frame is successfully copied, a "flags" and a "ready" events are
 * sent. Otherwise, a "failed" event is sent.
 */
static inline void
zwlr_screencopy_frame_v1_copy(struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1, struct wl_buffer *buffer)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_screencopy_frame_v1,
			 ZWLR_SCREENCOPY_FRAME_V1_COPY, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_screencopy_frame_v1), 0, buffer);
}

/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 *
 * Destroys the frame. This request can be sent at any time by the client.
 */
static inline void
zwlr_screencopy_frame_v1_destroy(struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_screencopy_frame_v1,
			 ZWLR_SCREENCOPY_FRAME_V1_DESTROY, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_screencopy_frame_v1), WL_MARSHAL_FLAG_DESTROY);
}

/**
 * @ingroup iface_zwlr_screencopy_frame_v1
 *
 * Same as copy, except it waits until there is damage to copy.
 */
static inline void
zwlr_screencopy_frame_v1_copy_with_damage(struct zwlr_screencopy_frame_v1 *zwlr_screencopy_frame_v1, struct wl_buffer *buffer)
{
	wl_proxy_marshal_flags((struct wl_proxy *) zwlr_screencopy_frame_v1,
			 ZWLR_SCREENCOPY_FRAME_V1_COPY_WITH_DAMAGE, NULL, wl_proxy_get_version((struct wl_proxy *) zwlr_screencopy_frame_v1), 0, buffer);
}

#ifdef  __cplusplus
}
#endif

#endif

/* ---- minimal xdg_popup_interface stub ----
 * wlr-layer-shell's get_popup() request signature references the
 * xdg_popup type (so a layer surface can be set as an xdg_popup's
 * parent). We never call get_popup() in this program, but the
 * generated marshalling code for zwlr_layer_surface_v1 still touches
 * the `xdg_popup_interface` symbol, so the linker needs it to exist.
 * Pulling in the full xdg-shell protocol (xdg_wm_base, xdg_toplevel,
 * xdg_positioner, ~2400 lines) just for this one unused symbol isn't
 * worth it - this empty placeholder satisfies the linker without
 * functioning as a real interface, since we never construct one. */
static const struct wl_interface xdg_popup_interface = {
	"xdg_popup", 1, 0, NULL, 0, NULL,
};

/* ---- wlr-layer-shell-unstable-v1 generated marshalling code ---- */
/* Generated by wayland-scanner 1.22.0 */

/*
 * Copyright © 2017 Drew DeVault
 *
 * Permission to use, copy, modify, distribute, and sell this
 * software and its documentation for any purpose is hereby granted
 * without fee, provided that the above copyright notice appear in
 * all copies and that both that copyright notice and this permission
 * notice appear in supporting documentation, and that the name of
 * the copyright holders not be used in advertising or publicity
 * pertaining to distribution of the software without specific,
 * written prior permission.  The copyright holders make no
 * representations about the suitability of this software for any
 * purpose.  It is provided "as is" without express or implied
 * warranty.
 *
 * THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
 * SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
 * FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
 * SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
 * WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
 * AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
 * ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
 * THIS SOFTWARE.
 */


#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_output_interface;
extern const struct wl_interface wl_surface_interface;
extern const struct wl_interface xdg_popup_interface;
extern const struct wl_interface zwlr_layer_surface_v1_interface;

static const struct wl_interface *wlr_layer_shell_unstable_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	&zwlr_layer_surface_v1_interface,
	&wl_surface_interface,
	&wl_output_interface,
	NULL,
	NULL,
	&xdg_popup_interface,
};

static const struct wl_message zwlr_layer_shell_v1_requests[] = {
	{ "get_layer_surface", "no?ous", wlr_layer_shell_unstable_v1_types + 4 },
	{ "destroy", "3", wlr_layer_shell_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_layer_shell_v1_interface = {
	"zwlr_layer_shell_v1", 4,
	2, zwlr_layer_shell_v1_requests,
	0, NULL,
};

static const struct wl_message zwlr_layer_surface_v1_requests[] = {
	{ "set_size", "uu", wlr_layer_shell_unstable_v1_types + 0 },
	{ "set_anchor", "u", wlr_layer_shell_unstable_v1_types + 0 },
	{ "set_exclusive_zone", "i", wlr_layer_shell_unstable_v1_types + 0 },
	{ "set_margin", "iiii", wlr_layer_shell_unstable_v1_types + 0 },
	{ "set_keyboard_interactivity", "u", wlr_layer_shell_unstable_v1_types + 0 },
	{ "get_popup", "o", wlr_layer_shell_unstable_v1_types + 9 },
	{ "ack_configure", "u", wlr_layer_shell_unstable_v1_types + 0 },
	{ "destroy", "", wlr_layer_shell_unstable_v1_types + 0 },
	{ "set_layer", "2u", wlr_layer_shell_unstable_v1_types + 0 },
};

static const struct wl_message zwlr_layer_surface_v1_events[] = {
	{ "configure", "uuu", wlr_layer_shell_unstable_v1_types + 0 },
	{ "closed", "", wlr_layer_shell_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_layer_surface_v1_interface = {
	"zwlr_layer_surface_v1", 4,
	9, zwlr_layer_surface_v1_requests,
	2, zwlr_layer_surface_v1_events,
};


/* ---- wlr-screencopy-unstable-v1 generated marshalling code ---- */
/* Generated by wayland-scanner 1.22.0 */

/*
 * Copyright © 2018 Simon Ser
 * Copyright © 2019 Andri Yngvason
 *
 * Permission is hereby granted, free of charge, to any person obtaining a
 * copy of this software and associated documentation files (the "Software"),
 * to deal in the Software without restriction, including without limitation
 * the rights to use, copy, modify, merge, publish, distribute, sublicense,
 * and/or sell copies of the Software, and to permit persons to whom the
 * Software is furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice (including the next
 * paragraph) shall be included in all copies or substantial portions of the
 * Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL
 * THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */


#ifndef __has_attribute
# define __has_attribute(x) 0  /* Compatibility with non-clang compilers. */
#endif

#if (__has_attribute(visibility) || defined(__GNUC__) && __GNUC__ >= 4)
#define WL_PRIVATE __attribute__ ((visibility("hidden")))
#else
#define WL_PRIVATE
#endif

extern const struct wl_interface wl_buffer_interface;
extern const struct wl_interface wl_output_interface;
extern const struct wl_interface zwlr_screencopy_frame_v1_interface;

static const struct wl_interface *wlr_screencopy_unstable_v1_types[] = {
	NULL,
	NULL,
	NULL,
	NULL,
	&zwlr_screencopy_frame_v1_interface,
	NULL,
	&wl_output_interface,
	&zwlr_screencopy_frame_v1_interface,
	NULL,
	&wl_output_interface,
	NULL,
	NULL,
	NULL,
	NULL,
	&wl_buffer_interface,
	&wl_buffer_interface,
};

static const struct wl_message zwlr_screencopy_manager_v1_requests[] = {
	{ "capture_output", "nio", wlr_screencopy_unstable_v1_types + 4 },
	{ "capture_output_region", "nioiiii", wlr_screencopy_unstable_v1_types + 7 },
	{ "destroy", "", wlr_screencopy_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_screencopy_manager_v1_interface = {
	"zwlr_screencopy_manager_v1", 3,
	3, zwlr_screencopy_manager_v1_requests,
	0, NULL,
};

static const struct wl_message zwlr_screencopy_frame_v1_requests[] = {
	{ "copy", "o", wlr_screencopy_unstable_v1_types + 14 },
	{ "destroy", "", wlr_screencopy_unstable_v1_types + 0 },
	{ "copy_with_damage", "2o", wlr_screencopy_unstable_v1_types + 15 },
};

static const struct wl_message zwlr_screencopy_frame_v1_events[] = {
	{ "buffer", "uuuu", wlr_screencopy_unstable_v1_types + 0 },
	{ "flags", "u", wlr_screencopy_unstable_v1_types + 0 },
	{ "ready", "uuu", wlr_screencopy_unstable_v1_types + 0 },
	{ "failed", "", wlr_screencopy_unstable_v1_types + 0 },
	{ "damage", "2uuuu", wlr_screencopy_unstable_v1_types + 0 },
	{ "linux_dmabuf", "3uuu", wlr_screencopy_unstable_v1_types + 0 },
	{ "buffer_done", "3", wlr_screencopy_unstable_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface zwlr_screencopy_frame_v1_interface = {
	"zwlr_screencopy_frame_v1", 3,
	3, zwlr_screencopy_frame_v1_requests,
	7, zwlr_screencopy_frame_v1_events,
};


/* =================================================================
 * End of inlined generated protocol code.
 * ================================================================= */

/* ---- tunables (kept identical in spirit to the X11 version) ---- */
#define GRID_CELLS   9
#define CELL_PX      16
#define CORNER_R     6

#define WIN_SIZE  (GRID_CELLS * CELL_PX)
#define HALF      (GRID_CELLS / 2)
#define GAP       20

#define SW_W  120
#define SW_H   52

/* ---------------------------------------------------------------- */
/* shm buffer helper                                                 */
/* ---------------------------------------------------------------- */

struct shm_buffer {
    struct wl_buffer *wl_buffer;
    void *data;
    int width, height, stride;
    size_t size;
    cairo_surface_t *cairo_surface; /* only used for the on-screen surface */
    bool busy; /* true while the compositor still owns this buffer */
};

static int create_shm_fd(size_t size)
{
    char name[] = "/px-wayland-XXXXXX";
    /* memfd_create avoids touching the filesystem at all */
    int fd = -1;
#if defined(__linux__)
    fd = syscall(SYS_memfd_create, "px-shm", 0);
#endif
    if (fd < 0) {
        /* fallback: shm_open with a unique name then unlink */
        for (int i = 0; i < 100; i++) {
            snprintf(name, sizeof(name), "/px-wayland-%06x", rand() & 0xffffff);
            fd = shm_open(name, O_RDWR | O_CREAT | O_EXCL, 0600);
            if (fd >= 0) { shm_unlink(name); break; }
            if (errno != EEXIST) break;
        }
    }
    if (fd < 0) return -1;
    if (ftruncate(fd, (off_t)size) < 0) { close(fd); return -1; }
    return fd;
}

static struct shm_buffer *shm_buffer_create(struct wl_shm *shm,
                                             int width, int height,
                                             uint32_t format)
{
    int stride = width * 4;
    size_t size = (size_t)stride * (size_t)height;

    int fd = create_shm_fd(size);
    if (fd < 0) { perror("create_shm_fd"); return NULL; }

    void *data = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (data == MAP_FAILED) { perror("mmap"); close(fd); return NULL; }

    struct wl_shm_pool *pool = wl_shm_create_pool(shm, fd, (int32_t)size);
    struct wl_buffer *buffer = wl_shm_pool_create_buffer(
        pool, 0, width, height, stride, format);
    wl_shm_pool_destroy(pool);
    close(fd);

    struct shm_buffer *sb = calloc(1, sizeof(*sb));
    sb->wl_buffer = buffer;
    sb->data = data;
    sb->width = width;
    sb->height = height;
    sb->stride = stride;
    sb->size = size;
    return sb;
}

static void shm_buffer_destroy(struct shm_buffer *sb)
{
    if (!sb) return;
    if (sb->cairo_surface) cairo_surface_destroy(sb->cairo_surface);
    if (sb->wl_buffer) wl_buffer_destroy(sb->wl_buffer);
    if (sb->data) munmap(sb->data, sb->size);
    free(sb);
}

static void on_buffer_release(void *data, struct wl_buffer *wl_buffer)
{
    (void)wl_buffer;
    struct shm_buffer *sb = data;
    sb->busy = false;
}

static const struct wl_buffer_listener buffer_release_listener = {
    .release = on_buffer_release,
};

/* ---------------------------------------------------------------- */
/* global app state                                                  */
/* ---------------------------------------------------------------- */

struct app {
    struct wl_display *display;
    struct wl_registry *registry;
    struct wl_compositor *compositor;
    struct wl_shm *shm;
    struct wl_seat *seat;
    struct wl_output *output;
    struct zwlr_layer_shell_v1 *layer_shell;
    struct zwlr_screencopy_manager_v1 *screencopy_mgr;

    struct wl_pointer *pointer;
    struct wl_keyboard *keyboard;

    struct xkb_context *xkb_ctx;
    struct xkb_keymap *xkb_keymap;
    struct xkb_state *xkb_state;

    /* output geometry, filled in via wl_output events */
    int32_t out_width, out_height;
    int32_t out_scale;

    /* the one-shot frozen screen capture */
    struct shm_buffer *capture;        /* raw captured pixels, ARGB8888/XRGB8888 */
    bool capture_ready;
    bool capture_failed;
    uint32_t capture_format;

    /* the on-screen overlay surface */
    struct wl_surface *surface;
    struct zwlr_layer_surface_v1 *layer_surface;
    bool configured;
    int32_t surf_width, surf_height;

    /* double buffer for the overlay drawing */
    struct shm_buffer *draw_bufs[2];
    int cur_buf;

    /* pointer state, surface-local coords (== output coords since fullscreen) */
    double ptr_x, ptr_y;
    bool have_ptr;

    bool running;
    bool clicked;
    int click_x, click_y;

    /* CLI opts (same semantics as the X11 build) */
    bool rgb;
    bool view;
    bool coordinate;
};

static struct app A; /* single global instance, simplest for a one-shot CLI tool */

/* forward decl: registry_global attaches this listener as soon as the
 * seat global is bound, but it's defined further down near the rest of
 * the seat/pointer/keyboard handlers. */
static const struct wl_seat_listener seat_listener;

/* ---------------------------------------------------------------- */
/* wl_registry                                                       */
/* ---------------------------------------------------------------- */

static void registry_global(void *data, struct wl_registry *registry,
                             uint32_t name, const char *interface,
                             uint32_t version)
{
    (void)data;
    if (strcmp(interface, wl_compositor_interface.name) == 0) {
        A.compositor = wl_registry_bind(registry, name,
                                         &wl_compositor_interface, 4);
    } else if (strcmp(interface, wl_shm_interface.name) == 0) {
        A.shm = wl_registry_bind(registry, name, &wl_shm_interface, 1);
    } else if (strcmp(interface, wl_seat_interface.name) == 0) {
        A.seat = wl_registry_bind(registry, name, &wl_seat_interface, 5);
        wl_seat_add_listener(A.seat, &seat_listener, NULL);
    } else if (strcmp(interface, wl_output_interface.name) == 0 && !A.output) {
        /* single-output: take the first one advertised, ignore the rest */
        A.output = wl_registry_bind(registry, name, &wl_output_interface, 2);
    } else if (strcmp(interface, zwlr_layer_shell_v1_interface.name) == 0) {
        A.layer_shell = wl_registry_bind(registry, name,
                                          &zwlr_layer_shell_v1_interface, 1);
    } else if (strcmp(interface, zwlr_screencopy_manager_v1_interface.name) == 0) {
        A.screencopy_mgr = wl_registry_bind(registry, name,
                                             &zwlr_screencopy_manager_v1_interface, 1);
    }
}

static void registry_global_remove(void *data, struct wl_registry *registry,
                                    uint32_t name)
{
    (void)data; (void)registry; (void)name;
}

static const struct wl_registry_listener registry_listener = {
    .global = registry_global,
    .global_remove = registry_global_remove,
};

/* ---------------------------------------------------------------- */
/* wl_output (need geometry for fullscreen sizing)                   */
/* ---------------------------------------------------------------- */

static void output_geometry(void *data, struct wl_output *wl_output,
                             int32_t x, int32_t y, int32_t pw, int32_t ph,
                             int32_t subpixel, const char *make,
                             const char *model, int32_t transform)
{
    (void)data; (void)wl_output; (void)x; (void)y; (void)pw; (void)ph;
    (void)subpixel; (void)make; (void)model; (void)transform;
}

static void output_mode(void *data, struct wl_output *wl_output,
                         uint32_t flags, int32_t width, int32_t height,
                         int32_t refresh)
{
    (void)data; (void)wl_output; (void)refresh;
    if (flags & WL_OUTPUT_MODE_CURRENT) {
        A.out_width = width;
        A.out_height = height;
    }
}

static void output_done(void *data, struct wl_output *wl_output)
{
    (void)data; (void)wl_output;
}

static void output_scale(void *data, struct wl_output *wl_output, int32_t factor)
{
    (void)data; (void)wl_output;
    A.out_scale = factor;
}

static const struct wl_output_listener output_listener = {
    .geometry = output_geometry,
    .mode = output_mode,
    .done = output_done,
    .scale = output_scale,
};

/* ---------------------------------------------------------------- */
/* wlr-screencopy: one-shot full-output capture                      */
/* ---------------------------------------------------------------- */

static void frame_buffer(void *data, struct zwlr_screencopy_frame_v1 *frame,
                          uint32_t format, uint32_t width, uint32_t height,
                          uint32_t stride)
{
    (void)data;
    /* allocate a matching shm buffer for the compositor to copy into */
    size_t size = (size_t)stride * (size_t)height;
    int fd = create_shm_fd(size);
    if (fd < 0) { perror("create_shm_fd (screencopy)"); A.capture_failed = true; return; }

    void *map = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (map == MAP_FAILED) { perror("mmap (screencopy)"); close(fd); A.capture_failed = true; return; }

    struct wl_shm_pool *pool = wl_shm_create_pool(A.shm, fd, (int32_t)size);
    struct wl_buffer *buffer = wl_shm_pool_create_buffer(
        pool, 0, (int32_t)width, (int32_t)height, (int32_t)stride, format);
    wl_shm_pool_destroy(pool);
    close(fd);

    struct shm_buffer *sb = calloc(1, sizeof(*sb));
    sb->wl_buffer = buffer;
    sb->data = map;
    sb->width = (int)width;
    sb->height = (int)height;
    sb->stride = (int)stride;
    sb->size = size;
    A.capture = sb;
    A.capture_format = format;

    zwlr_screencopy_frame_v1_copy(frame, buffer);
}

static void frame_flags(void *data, struct zwlr_screencopy_frame_v1 *frame,
                         uint32_t flags)
{
    (void)data; (void)frame; (void)flags;
}

/* Normalize the just-captured buffer to XRGB/ARGB byte order in place,
 * if the compositor handed us a BGR-variant format instead. Done once
 * here rather than per-pixel in sample_capture/capture_as_cairo_surface,
 * since the latter is called on every redraw (every pointer motion) and
 * would otherwise re-swap the whole screen's worth of pixels every
 * frame for no reason - normalizing once up front lets the rest of the
 * code (and cairo, which has no native BGR format) just always assume
 * RGB byte order from here on. */
static void normalize_capture_to_rgb_order(void)
{
    if (!A.capture) return;
    if (A.capture_format != WL_SHM_FORMAT_XBGR8888 &&
        A.capture_format != WL_SHM_FORMAT_ABGR8888) {
        return; /* already RGB-ordered (or an unexpected format we leave alone) */
    }

    uint8_t *base = (uint8_t *)A.capture->data;
    for (int y = 0; y < A.capture->height; y++) {
        uint8_t *row = base + (size_t)y * A.capture->stride;
        for (int x = 0; x < A.capture->width; x++) {
            uint8_t *px = row + (size_t)x * 4;
            uint8_t tmp = px[0]; /* R <-> B */
            px[0] = px[2];
            px[2] = tmp;
        }
    }

    A.capture_format = (A.capture_format == WL_SHM_FORMAT_ABGR8888)
                        ? WL_SHM_FORMAT_ARGB8888 : WL_SHM_FORMAT_XRGB8888;
}

static void frame_ready(void *data, struct zwlr_screencopy_frame_v1 *frame,
                         uint32_t tv_sec_hi, uint32_t tv_sec_lo, uint32_t tv_nsec)
{
    (void)data; (void)tv_sec_hi; (void)tv_sec_lo; (void)tv_nsec;
    normalize_capture_to_rgb_order();
    A.capture_ready = true;
    zwlr_screencopy_frame_v1_destroy(frame);
}

static void frame_failed(void *data, struct zwlr_screencopy_frame_v1 *frame)
{
    (void)data;
    A.capture_failed = true;
    zwlr_screencopy_frame_v1_destroy(frame);
}

static const struct zwlr_screencopy_frame_v1_listener frame_listener = {
    .buffer = frame_buffer,
    .flags = frame_flags,
    .ready = frame_ready,
    .failed = frame_failed,
};

/* ---------------------------------------------------------------- */
/* helpers shared with the X11 version: placement + drawing          */
/* ---------------------------------------------------------------- */

/* Same logic as the X11 place_win(), but operating in surface-local
 * (== output-local, since we're fullscreen) coordinates instead of
 * moving a separate top-level window. */
static void place_panel(int mx, int my, int sw, int sh,
                         int win_w, int win_h,
                         bool right_side, bool bottom_side,
                         int *out_x, int *out_y)
{
    *out_x = right_side  ? mx + GAP : mx - GAP - win_w;
    *out_y = bottom_side ? my + GAP : my - GAP - win_h;
    if (*out_x < 0)          *out_x = 0;
    if (*out_y < 0)          *out_y = 0;
    if (*out_x + win_w > sw) *out_x = sw - win_w;
    if (*out_y + win_h > sh) *out_y = sh - win_h;
}

/* Read one pixel from the frozen capture buffer.
 *
 * Safe to assume XRGB/ARGB byte order unconditionally here: whatever
 * format the compositor actually handed back in frame_buffer(), it's
 * already been normalized to RGB order in-place by
 * normalize_capture_to_rgb_order() before A.capture_ready was set, so
 * this never runs against raw BGR data. (See that function's comment
 * for why the original version of this code - which assumed RGB order
 * without checking - produced a colour tint on compositors that hand
 * back XBGR8888/ABGR8888.) */
static void sample_capture(int x, int y, int *r, int *g, int *b)
{
    if (!A.capture || x < 0 || y < 0 || x >= A.capture->width || y >= A.capture->height) {
        *r = *g = *b = 0;
        return;
    }
    uint8_t *row = (uint8_t *)A.capture->data + (size_t)y * A.capture->stride;
    uint32_t px;
    memcpy(&px, row + (size_t)x * 4, 4);
    *b = (px >>  0) & 0xff;
    *g = (px >>  8) & 0xff;
    *r = (px >> 16) & 0xff;
}

static cairo_surface_t *capture_as_cairo_surface(void)
{
    if (!A.capture) return NULL;
    /* Safe to wrap the buffer directly with no copy: by this point
     * A.capture_format has been normalized (in frame_ready, via
     * normalize_capture_to_rgb_order) to always be either ARGB8888 or
     * XRGB8888, both of which match cairo's ARGB32/RGB24 byte layout
     * exactly. Cairo has no native format for the BGR variants the
     * compositor may have originally handed back, which is why that
     * normalization step exists rather than branching here. */
    cairo_format_t fmt = (A.capture_format == WL_SHM_FORMAT_ARGB8888)
                          ? CAIRO_FORMAT_ARGB32 : CAIRO_FORMAT_RGB24;
    return cairo_image_surface_create_for_data(
        (unsigned char *)A.capture->data, fmt,
        A.capture->width, A.capture->height, A.capture->stride);
}

static void draw_magnifier(cairo_t *cr, int panel_x, int panel_y, int mx, int my)
{
    int sw = A.capture ? A.capture->width  : A.surf_width;
    int sh = A.capture ? A.capture->height : A.surf_height;

    int sx = mx - HALF, sy = my - HALF;
    if (sx < 0) sx = 0;
    if (sy < 0) sy = 0;
    if (sx + GRID_CELLS > sw) sx = sw - GRID_CELLS;
    if (sy + GRID_CELLS > sh) sy = sh - GRID_CELLS;

    cairo_save(cr);
    cairo_translate(cr, panel_x, panel_y);

    for (int row = 0; row < GRID_CELLS; row++) {
        for (int col = 0; col < GRID_CELLS; col++) {
            int r, g, b;
            sample_capture(sx + col, sy + row, &r, &g, &b);
            double cx = col * CELL_PX, cy = row * CELL_PX;
            bool top = (row == 0), bot = (row == GRID_CELLS - 1);
            bool left = (col == 0), right = (col == GRID_CELLS - 1);
            bool corner = (CORNER_R > 0) && (top || bot) && (left || right);

            cairo_set_source_rgb(cr, r / 255.0, g / 255.0, b / 255.0);

            if (corner) {
                /* rounded outer corners only, square everywhere else */
                double rad = CORNER_R;
                cairo_new_path(cr);
                double x0 = cx, y0 = cy, x1 = cx + CELL_PX, y1 = cy + CELL_PX;
                double rad_tl = (top && left)   ? rad : 0;
                double rad_tr = (top && right)  ? rad : 0;
                double rad_bl = (bot && left)   ? rad : 0;
                double rad_br = (bot && right)  ? rad : 0;
                cairo_move_to(cr, x0 + rad_tl, y0);
                cairo_line_to(cr, x1 - rad_tr, y0);
                if (rad_tr > 0) cairo_arc(cr, x1 - rad_tr, y0 + rad_tr, rad_tr, -M_PI/2, 0);
                else cairo_line_to(cr, x1, y0);
                cairo_line_to(cr, x1, y1 - rad_br);
                if (rad_br > 0) cairo_arc(cr, x1 - rad_br, y1 - rad_br, rad_br, 0, M_PI/2);
                else cairo_line_to(cr, x1, y1);
                cairo_line_to(cr, x0 + rad_bl, y1);
                if (rad_bl > 0) cairo_arc(cr, x0 + rad_bl, y1 - rad_bl, rad_bl, M_PI/2, M_PI);
                else cairo_line_to(cr, x0, y1);
                cairo_line_to(cr, x0, y0 + rad_tl);
                if (rad_tl > 0) cairo_arc(cr, x0 + rad_tl, y0 + rad_tl, rad_tl, M_PI, 3*M_PI/2);
                else cairo_line_to(cr, x0, y0);
                cairo_close_path(cr);
                cairo_fill(cr);
            } else {
                cairo_rectangle(cr, cx, cy, CELL_PX, CELL_PX);
                cairo_fill(cr);
            }

            /* grid lines */
            cairo_set_source_rgb(cr, 0, 0, 0);
            cairo_set_line_width(cr, 1);
            if (col < GRID_CELLS - 1) {
                cairo_move_to(cr, cx + CELL_PX - 0.5, cy);
                cairo_line_to(cr, cx + CELL_PX - 0.5, cy + CELL_PX);
                cairo_stroke(cr);
            }
            if (row < GRID_CELLS - 1) {
                cairo_move_to(cr, cx, cy + CELL_PX - 0.5);
                cairo_line_to(cr, cx + CELL_PX, cy + CELL_PX - 0.5);
                cairo_stroke(cr);
            }
        }
    }

    /* center cell highlight outline, same as X11 version */
    double ccx = HALF * CELL_PX, ccy = HALF * CELL_PX;
    cairo_set_source_rgb(cr, 1, 1, 1);
    cairo_set_line_width(cr, 1);
    cairo_rectangle(cr, ccx + 0.5, ccy + 0.5, CELL_PX - 1, CELL_PX - 1);
    cairo_stroke(cr);

    /* border around whole magnifier */
    cairo_set_source_rgb(cr, 0x44/255.0, 0x44/255.0, 0x44/255.0);
    cairo_set_line_width(cr, 1);
    cairo_rectangle(cr, 0.5, 0.5, WIN_SIZE - 1, WIN_SIZE - 1);
    cairo_stroke(cr);

    cairo_restore(cr);
}

static void draw_swatch(cairo_t *cr, int panel_x, int panel_y,
                         int r, int g, int b)
{
    cairo_save(cr);
    cairo_translate(cr, panel_x, panel_y);

    cairo_set_source_rgb(cr, 0x1a/255.0, 0x1a/255.0, 0x1a/255.0);
    cairo_rectangle(cr, 0, 0, SW_W, SW_H);
    cairo_fill(cr);

    cairo_set_source_rgb(cr, r / 255.0, g / 255.0, b / 255.0);
    cairo_rectangle(cr, 0, 0, SW_W / 3.0, SW_H);
    cairo_fill(cr);

    cairo_set_source_rgb(cr, 0x44/255.0, 0x44/255.0, 0x44/255.0);
    cairo_set_line_width(cr, 1);
    cairo_move_to(cr, SW_W / 3.0, 0);
    cairo_line_to(cr, SW_W / 3.0, SW_H);
    cairo_stroke(cr);

    char hex[12], rgb_str[24];
    snprintf(hex, sizeof(hex), "#%02x%02x%02x", r, g, b);
    snprintf(rgb_str, sizeof(rgb_str), "%d %d %d", r, g, b);

    cairo_set_source_rgb(cr, 1, 1, 1);
    cairo_select_font_face(cr, "monospace", CAIRO_FONT_SLANT_NORMAL, CAIRO_FONT_WEIGHT_NORMAL);
    cairo_set_font_size(cr, 13);
    cairo_move_to(cr, SW_W / 3.0 + 7, 22);
    cairo_show_text(cr, hex);
    cairo_move_to(cr, SW_W / 3.0 + 7, 40);
    cairo_show_text(cr, rgb_str);

    cairo_set_source_rgb(cr, 0x44/255.0, 0x44/255.0, 0x44/255.0);
    cairo_rectangle(cr, 0.5, 0.5, SW_W - 1, SW_H - 1);
    cairo_stroke(cr);

    cairo_restore(cr);
}

/* Render one full frame: background = frozen desktop capture (so the
 * picker still "sees" the screen), plus magnifier + swatch panels near
 * the simulated pointer. Mirrors update_both() from the X11 version. */
static void render_frame(void)
{
    if (!A.configured || A.surf_width <= 0 || A.surf_height <= 0) return;

    /* pick whichever of the two draw buffers the compositor isn't
     * currently holding onto; if both are busy (shouldn't normally
     * happen with only two in flight) dispatch until one frees up,
     * rather than attaching a buffer the compositor may still be
     * reading from. */
    int idx = A.cur_buf;
    if (A.draw_bufs[idx]->busy) idx ^= 1;
    int spins = 0;
    while (A.draw_bufs[idx]->busy && spins++ < 50) {
        wl_display_dispatch_pending(A.display);
        wl_display_flush(A.display);
    }
    struct shm_buffer *buf = A.draw_bufs[idx];
    if (!buf) return;

    cairo_t *cr = cairo_create(buf->cairo_surface);

    /* background: the frozen capture, scaled/positioned 1:1 */
    cairo_surface_t *bg = capture_as_cairo_surface();
    if (bg) {
        cairo_set_source_surface(cr, bg, 0, 0);
        cairo_paint(cr);
        cairo_surface_destroy(bg);
    } else {
        cairo_set_source_rgb(cr, 0, 0, 0);
        cairo_paint(cr);
    }

    int mx = (int)A.ptr_x, my = (int)A.ptr_y;
    int sw = A.surf_width, sh = A.surf_height;

    bool prev_right  = (mx + GAP + WIN_SIZE <= sw);
    bool prev_bottom = (my + GAP + WIN_SIZE <= sh);
    bool sw_right  = !prev_right;
    bool sw_bottom = prev_bottom;

    int px, py, swx, swy;
    place_panel(mx, my, sw, sh, WIN_SIZE, WIN_SIZE, prev_right, prev_bottom, &px, &py);
    place_panel(mx, my, sw, sh, SW_W, SW_H, sw_right, sw_bottom, &swx, &swy);

    draw_magnifier(cr, px, py, mx, my);

    int r, g, b;
    sample_capture(mx, my, &r, &g, &b);
    draw_swatch(cr, swx, swy, r, g, b);

    cairo_destroy(cr);

    buf->busy = true;
    wl_surface_attach(A.surface, buf->wl_buffer, 0, 0);
    wl_surface_damage_buffer(A.surface, 0, 0, A.surf_width, A.surf_height);
    wl_surface_commit(A.surface);

    A.cur_buf = idx ^ 1;
}

/* ---------------------------------------------------------------- */
/* layer surface configure handshake                                 */
/* ---------------------------------------------------------------- */

static void ensure_draw_buffers(int width, int height)
{
    for (int i = 0; i < 2; i++) {
        if (A.draw_bufs[i]) shm_buffer_destroy(A.draw_bufs[i]);
        A.draw_bufs[i] = shm_buffer_create(A.shm, width, height, WL_SHM_FORMAT_ARGB8888);
        A.draw_bufs[i]->cairo_surface = cairo_image_surface_create_for_data(
            (unsigned char *)A.draw_bufs[i]->data, CAIRO_FORMAT_ARGB32,
            width, height, A.draw_bufs[i]->stride);
        wl_buffer_add_listener(A.draw_bufs[i]->wl_buffer, &buffer_release_listener, A.draw_bufs[i]);
    }
}

static void layer_surface_configure(void *data,
                                     struct zwlr_layer_surface_v1 *surf,
                                     uint32_t serial, uint32_t width, uint32_t height)
{
    (void)data;
    A.surf_width = (int32_t)width;
    A.surf_height = (int32_t)height;
    zwlr_layer_surface_v1_ack_configure(surf, serial);
    ensure_draw_buffers(A.surf_width, A.surf_height);
    A.configured = true;
    render_frame();
}

static void layer_surface_closed(void *data, struct zwlr_layer_surface_v1 *surf)
{
    (void)data; (void)surf;
    A.running = false;
}

static const struct zwlr_layer_surface_v1_listener layer_surface_listener = {
    .configure = layer_surface_configure,
    .closed = layer_surface_closed,
};

/* ---------------------------------------------------------------- */
/* pointer + keyboard                                                 */
/* ---------------------------------------------------------------- */

static void pointer_enter(void *data, struct wl_pointer *ptr, uint32_t serial,
                           struct wl_surface *surface, wl_fixed_t sx, wl_fixed_t sy)
{
    (void)data; (void)ptr; (void)serial; (void)surface;
    A.ptr_x = wl_fixed_to_double(sx);
    A.ptr_y = wl_fixed_to_double(sy);
    A.have_ptr = true;
}

static void pointer_leave(void *data, struct wl_pointer *ptr, uint32_t serial,
                           struct wl_surface *surface)
{
    (void)data; (void)ptr; (void)serial; (void)surface;
}

static void pointer_motion(void *data, struct wl_pointer *ptr, uint32_t time,
                            wl_fixed_t sx, wl_fixed_t sy)
{
    (void)data; (void)ptr; (void)time;
    A.ptr_x = wl_fixed_to_double(sx);
    A.ptr_y = wl_fixed_to_double(sy);
    A.have_ptr = true;
    render_frame();
}

static void pointer_button(void *data, struct wl_pointer *ptr, uint32_t serial,
                            uint32_t time, uint32_t button, uint32_t state)
{
    (void)data; (void)ptr; (void)serial; (void)time;
    if (button == BTN_LEFT && state == WL_POINTER_BUTTON_STATE_PRESSED) {
        A.clicked = true;
        A.click_x = (int)A.ptr_x;
        A.click_y = (int)A.ptr_y;
        A.running = false;
    }
}

static void pointer_axis(void *data, struct wl_pointer *ptr, uint32_t time,
                          uint32_t axis, wl_fixed_t value)
{
    (void)data; (void)ptr; (void)time; (void)axis; (void)value;
}

static void pointer_frame(void *data, struct wl_pointer *ptr)
{
    (void)data; (void)ptr;
}

static void pointer_axis_source(void *data, struct wl_pointer *ptr, uint32_t source)
{ (void)data; (void)ptr; (void)source; }
static void pointer_axis_stop(void *data, struct wl_pointer *ptr, uint32_t time, uint32_t axis)
{ (void)data; (void)ptr; (void)time; (void)axis; }
static void pointer_axis_discrete(void *data, struct wl_pointer *ptr, uint32_t axis, int32_t discrete)
{ (void)data; (void)ptr; (void)axis; (void)discrete; }

static const struct wl_pointer_listener pointer_listener = {
    .enter = pointer_enter,
    .leave = pointer_leave,
    .motion = pointer_motion,
    .button = pointer_button,
    .axis = pointer_axis,
    .frame = pointer_frame,
    .axis_source = pointer_axis_source,
    .axis_stop = pointer_axis_stop,
    .axis_discrete = pointer_axis_discrete,
};

static void keyboard_keymap(void *data, struct wl_keyboard *kb, uint32_t format,
                             int32_t fd, uint32_t size)
{
    (void)data; (void)kb;
    if (format != WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1) { close(fd); return; }
    char *map_str = mmap(NULL, size, PROT_READ, MAP_PRIVATE, fd, 0);
    if (map_str == MAP_FAILED) { close(fd); return; }
    if (A.xkb_keymap) xkb_keymap_unref(A.xkb_keymap);
    A.xkb_keymap = xkb_keymap_new_from_string(A.xkb_ctx, map_str,
                                               XKB_KEYMAP_FORMAT_TEXT_V1,
                                               XKB_KEYMAP_COMPILE_NO_FLAGS);
    munmap(map_str, size);
    close(fd);
    if (A.xkb_state) xkb_state_unref(A.xkb_state);
    A.xkb_state = xkb_state_new(A.xkb_keymap);
}

static void keyboard_enter(void *data, struct wl_keyboard *kb, uint32_t serial,
                            struct wl_surface *surface, struct wl_array *keys)
{ (void)data; (void)kb; (void)serial; (void)surface; (void)keys; }

static void keyboard_leave(void *data, struct wl_keyboard *kb, uint32_t serial,
                            struct wl_surface *surface)
{ (void)data; (void)kb; (void)serial; (void)surface; }

static void keyboard_key(void *data, struct wl_keyboard *kb, uint32_t serial,
                          uint32_t time, uint32_t key, uint32_t state)
{
    (void)data; (void)kb; (void)serial; (void)time;
    /* Any keypress exits, mirroring the X11 build's KeyPress handler. */
    if (state == WL_KEYBOARD_KEY_STATE_PRESSED) {
        A.running = false;
    }
    (void)key;
}

static void keyboard_modifiers(void *data, struct wl_keyboard *kb, uint32_t serial,
                                uint32_t mods_depressed, uint32_t mods_latched,
                                uint32_t mods_locked, uint32_t group)
{
    (void)data; (void)kb; (void)serial;
    if (A.xkb_state) {
        xkb_state_update_mask(A.xkb_state, mods_depressed, mods_latched,
                               mods_locked, 0, 0, group);
    }
}

static void keyboard_repeat_info(void *data, struct wl_keyboard *kb,
                                  int32_t rate, int32_t delay)
{ (void)data; (void)kb; (void)rate; (void)delay; }

static const struct wl_keyboard_listener keyboard_listener = {
    .keymap = keyboard_keymap,
    .enter = keyboard_enter,
    .leave = keyboard_leave,
    .key = keyboard_key,
    .modifiers = keyboard_modifiers,
    .repeat_info = keyboard_repeat_info,
};

static void seat_capabilities(void *data, struct wl_seat *seat, uint32_t caps)
{
    (void)data;
    if ((caps & WL_SEAT_CAPABILITY_POINTER) && !A.pointer) {
        A.pointer = wl_seat_get_pointer(seat);
        wl_pointer_add_listener(A.pointer, &pointer_listener, NULL);
    }
    if ((caps & WL_SEAT_CAPABILITY_KEYBOARD) && !A.keyboard) {
        A.keyboard = wl_seat_get_keyboard(seat);
        wl_keyboard_add_listener(A.keyboard, &keyboard_listener, NULL);
    }
}

static void seat_name(void *data, struct wl_seat *seat, const char *name)
{ (void)data; (void)seat; (void)name; }

static const struct wl_seat_listener seat_listener = {
    .capabilities = seat_capabilities,
    .name = seat_name,
};

/* ---------------------------------------------------------------- */
/* clipboard: wl-copy is the standard wlroots-ecosystem helper for    */
/* this, same role xclip played in the X11 build.                    */
/* ---------------------------------------------------------------- */

static void copy_to_clipboard(const char *text)
{
    char cmd[256];
    snprintf(cmd, sizeof(cmd), "printf '%s' | wl-copy", text);
    system(cmd);
}

/* ---------------------------------------------------------------- */
/* main                                                               */
/* ---------------------------------------------------------------- */

int main(int argc, char **argv)
{
    int c;
    memset(&A, 0, sizeof(A));
    A.out_scale = 1;

    while ((c = getopt(argc, argv, "hxrvcat:")) != -1) {
        switch (c) {
            case 'h':
                printf("Usage: px [-h] [-xrvca] [-t seconds]\n\n"
                       "Click left mouse button to pick a color. Any key exits.\n\n"
                       "Options:\n"
                       "  -h        display this message and exit\n"
                       "  -x        print in hexadecimal only (default)\n"
                       "  -r        print in rgb\n"
                       "  -v        show color swatch in terminal\n"
                       "  -c        print coordinate\n"
                       "  -a        run px with the -xvc options\n"
                       "  -t <n>    sleep for n seconds\n\n"
                       "Requires a wlroots-based compositor "
                       "(wlr-layer-shell-unstable-v1 + wlr-screencopy-unstable-v1).\n"
                       "Tweak: GRID_CELLS, CELL_PX, CORNER_R, SW_W, SW_H at top of source\n");
                return 0;
            case 'x': A.rgb = false; break;
            case 'r': A.rgb = true; break;
            case 'v': A.view = true; break;
            case 'c': A.coordinate = true; break;
            case 'a': A.rgb = false; A.view = true; A.coordinate = true; break;
            case 't': sleep((unsigned)atoi(optarg)); break;
        }
    }

    A.display = wl_display_connect(NULL);
    if (!A.display) {
        fprintf(stderr, "px: cannot connect to a Wayland display\n");
        return 1;
    }

    srand((unsigned)time(NULL) ^ (unsigned)getpid());

    A.xkb_ctx = xkb_context_new(XKB_CONTEXT_NO_FLAGS);

    A.registry = wl_display_get_registry(A.display);
    wl_registry_add_listener(A.registry, &registry_listener, NULL);
    wl_display_roundtrip(A.display);

    if (!A.compositor || !A.shm || !A.seat || !A.output) {
        fprintf(stderr, "px: missing a required Wayland global "
                        "(compositor/shm/seat/output)\n");
        return 1;
    }
    if (!A.layer_shell) {
        fprintf(stderr, "px: compositor does not support "
                        "wlr-layer-shell-unstable-v1 (needs a wlroots-based "
                        "compositor, e.g. Sway, Hyprland, river)\n");
        return 1;
    }
    if (!A.screencopy_mgr) {
        fprintf(stderr, "px: compositor does not support "
                        "wlr-screencopy-unstable-v1 (needs a wlroots-based "
                        "compositor, e.g. Sway, Hyprland, river)\n");
        return 1;
    }

    wl_output_add_listener(A.output, &output_listener, NULL);
    wl_display_roundtrip(A.display); /* collect output geometry/mode/scale */

    /* --- one-shot full-output screencopy capture (replaces XGetImage on root) --- */
    struct zwlr_screencopy_frame_v1 *frame =
        zwlr_screencopy_manager_v1_capture_output(A.screencopy_mgr, 0, A.output);
    zwlr_screencopy_frame_v1_add_listener(frame, &frame_listener, NULL);

    while (!A.capture_ready && !A.capture_failed) {
        if (wl_display_dispatch(A.display) < 0) {
            fprintf(stderr, "px: connection error while waiting for screencopy\n");
            return 1;
        }
    }
    if (A.capture_failed || !A.capture) {
        fprintf(stderr, "px: screencopy capture failed\n");
        return 1;
    }

    /* --- fullscreen overlay layer surface (replaces XGrabPointer/XGrabKeyboard) --- */
    A.surface = wl_compositor_create_surface(A.compositor);
    A.layer_surface = zwlr_layer_shell_v1_get_layer_surface(
        A.layer_shell, A.surface, A.output,
        ZWLR_LAYER_SHELL_V1_LAYER_OVERLAY, "px");

    zwlr_layer_surface_v1_set_anchor(A.layer_surface,
        ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP | ZWLR_LAYER_SURFACE_V1_ANCHOR_BOTTOM |
        ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT | ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT);
    zwlr_layer_surface_v1_set_size(A.layer_surface, A.capture->width, A.capture->height);
    zwlr_layer_surface_v1_set_exclusive_zone(A.layer_surface, -1);
    zwlr_layer_surface_v1_set_keyboard_interactivity(A.layer_surface,
        ZWLR_LAYER_SURFACE_V1_KEYBOARD_INTERACTIVITY_EXCLUSIVE);
    zwlr_layer_surface_v1_add_listener(A.layer_surface, &layer_surface_listener, NULL);

    wl_surface_commit(A.surface);

    /* set the crosshair cursor shape via the wp_cursor_shape protocol
     * would be the "correct" modern approach; many wlroots compositors
     * still default to showing a normal pointer over client surfaces,
     * which is an acceptable trade-off here - the magnifier serves the
     * same purpose the crosshair cursor did in the X11 build. */

    A.running = true;
    while (A.running) {
        if (wl_display_dispatch(A.display) < 0) break;
    }

    if (A.clicked) {
        int r, g, b;
        sample_capture(A.click_x, A.click_y, &r, &g, &b);
        uint32_t color = ((uint32_t)r << 16) | ((uint32_t)g << 8) | (uint32_t)b;

        char out[128];
        if (A.rgb)
            snprintf(out, sizeof(out), "%d, %d, %d", r, g, b);
        else
            snprintf(out, sizeof(out), "#%06x", color);

        copy_to_clipboard(out);
        printf("%s", out);

        if (A.view)
            printf("  \033[48;2;%d;%d;%dm      \033[0m", r, g, b);
        if (A.coordinate)
            printf("  (%dx%d)", A.click_x, A.click_y);
        putchar('\n');
    }

    /* cleanup */
    if (A.layer_surface) zwlr_layer_surface_v1_destroy(A.layer_surface);
    if (A.surface) wl_surface_destroy(A.surface);
    for (int i = 0; i < 2; i++) shm_buffer_destroy(A.draw_bufs[i]);
    shm_buffer_destroy(A.capture);
    if (A.xkb_state) xkb_state_unref(A.xkb_state);
    if (A.xkb_keymap) xkb_keymap_unref(A.xkb_keymap);
    if (A.xkb_ctx) xkb_context_unref(A.xkb_ctx);
    wl_display_disconnect(A.display);

    return A.clicked ? 0 : 1;
}
